# Generated by Django 4.0.2 on 2022-06-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='predicted_age',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='predicted_gender',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.category'),
        ),
    ]
