# Generated by Django 4.0.2 on 2022-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_customer_age_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tmp_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
