# Generated by Django 4.0.2 on 2022-06-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_tmp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tmp_image',
        ),
    ]
