# Generated by Django 4.0.2 on 2022-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_tmp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
